### ISSUE TITLE
Blank ResourceProvider

### ISSUE THREAD

**Issue by DantheCodingGui** [Comcast/resourceprovider#28]
Hi,

Love the idea for the library so thought I'd try integrating it into my project as per the instructions and after building the project I keep getting the same blank ResourceProvider class.

```
public class ResourceProvider {
  private Context context;

  public ResourceProvider(Context context) {
    this.context = context;
  }
}
```

I've seen the the class is generated correctly for the sample project and a blank project that I tested on. I've also ensured that kapt correctErrorTypes is set to true.

I assume it is clashing with something else in the project but since I can't see any errors or warning in the build logs I don't really know where to start.

Just wanted to know if there's anywhere specific I should start looking or any particular libraries that clash with ResourceProvider. Thanks.

**Comment by DantheCodingGui** [comment]
Fixed original problem, the library doesn't generate the providers when the application is not in the root package. 

Now when I try and build there seems to be some conflict with DataBinding, as it now errors during a build. 

Again if there's any fix you know of please let me know. Thanks

**Comment by dapp** [comment]
Can you post a build log?

**Comment by DantheCodingGui** [comment]
Looks like it was a false error due to something else.

Almost got it completely working. Going to open another issue about it though.
