### ISSUE TITLE
StringProvider not generated on it's own

### ISSUE THREAD

**Issue by DantheCodingGui** [Comcast/resourceprovider#29]
Almost got this library working in my project completely.

The only problem I'm still having now is a strange issue where StringProvider is only ever generated if every single other provider is generated (ie not generated if any flags in the application annotation are set to false).

While not ideal, for testing purposes I attempted to just take all providers to see if it worked finally. It was here that I found that any resource names that end in an underscore would cause the build to fail. Normally this would just be a simple refactoring fix, but unfortunately library resources are also taken into account and for some reason Instabug uses some resources with trailing underscores (which I can't do anything about).

I don't know if the underscore issue is fixable but it isn't as important for my use case since I believe it only crashes for me if I generate the DrawableProvider. 

Also a small thing I also found while trying to get this library to play nicely with my project. Apparently the Application subclass annotated with RpApplication needs to be in the root of the project for the ResourceProvider to be generated correctly. It might be worth mentioning this in the ReadMe in case anyone else runs into this issue.

Thanks for reading this mini essay.

**Comment by DantheCodingGui** [comment]
Any updates on the StringProvider generation issue?

**Comment by dapp** [comment]
I haven't tested this, I'll try to look into it soon

**Comment by dapp** [comment]
Fixed and released in version 1.2.1
