### ISSUE TITLE
Provider classes not generated with newest version of gradle build tools

### ISSUE THREAD

**Issue by DantheCodingGui** [Comcast/resourceprovider#36]
Hi,

Just updated all the dependencies in my project, and no providers classes were generated on the latest gradle build tools version (3.6.1 as of this date)

Thanks

**Comment by dapp** [comment]
Opened a stackoverflow for this https://stackoverflow.com/questions/61146024/android-r-class-not-available-during-annotation-processing-with-android-gradle-p

**Comment by dapp** [comment]
@DantheCodingGui the last gradle version that will work is 3.5.0

I would hold there until we figure this out.  apologies

**Comment by dapp** [comment]
@DantheCodingGui 

I've rewritten resource provider as a Gradle Plugin for compatibility with AGP 3.6.+.  As soon as it's available I'll let you know.  Temporarily, you might be able to get working by using 

`android.generateRJava=true `

as outlined here: https://issuetracker.google.com/issues/153964091

**Comment by DantheCodingGui** [comment]
@dapp 

I've been holding at 3.5.0 for a while now anyway so no problems, 

Thanks for looking into this.

**Comment by dapp** [comment]
@DantheCodingGui the new plugin is published and ready.   Usage details are here:

https://medium.com/@daptronic/the-new-resourceprovider-9ad444d78be0

I'll  try to publish the source soon.  Comment here or on Medium if you have any problems.

**Comment by DantheCodingGui** [comment]
@dapp 

Awesome! Much appreciated, I'll try it when I next have the chance.

If I have any problems i'll open a new issue for it.

**Comment by dapp** [comment]
@DantheCodingGui  : https://github.com/Comcast/resourceprovider2

Version 1.1.0 should be available soon, it has support for Kotlin projects.
